name: validate
on:
  push:
    branches:
    - main

jobs:
  env_validate:
    name: validate
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest", "windows-2016"]
        #python-version: ['3.7', '3.8']
    steps:  
      - name: Clone repo  
        uses: actions/checkout@v3
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: torchgeo
          auto-update-conda: false
          channels: pytorch,conda-forge,esri,open3d-admin
          channel-priority: strict
          environment-file: environment.yml
          python-version: 3.7 
      - run: |
          conda info
          conda list