name: validate conda environment
on:
  push:
    branches:
    - main

jobs:
  env_validate:
    name: Validate conda environment
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ['3.7', '3.8']
    steps:    
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: torchgeo
          auto-update-conda: false
          channels: conda-forge
          channel-priority: strict
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          
      - run: |
          conda info
          conda list